// Central data-testid registry for the Imagen Studio app.
export const TID = {
  sidebar: {
    nav: "sidebar-nav",
    studio: "sidebar-link-studio",
    bulk: "sidebar-link-bulk",
    presets: "sidebar-link-presets",
    gallery: "sidebar-link-gallery",
    settings: "sidebar-link-settings",
  },
  studio: {
    root: "studio-page",
    promptInput: "studio-prompt-input",
    negativePromptToggle: "studio-negative-prompt-toggle",
    negativePromptInput: "studio-negative-prompt-input",
    modelSelect: "studio-model-select",
    aspectRatio: (r) => `studio-aspect-${r.replace(":", "x")}`,
    countSelect: "studio-count-select",
    generateBtn: "studio-generate-button",
    presetChip: (id) => `studio-preset-chip-${id}`,
    referenceUpload: "studio-reference-upload",
    referenceCard: (i) => `studio-reference-card-${i}`,
    referenceRemove: (i) => `studio-reference-remove-${i}`,
    referenceStrength: "studio-reference-strength",
    analyzeBtn: "studio-analyze-reference-button",
    styleDescription: "studio-style-description",
    saveAsPresetBtn: "studio-save-as-preset-button",
    resultCard: (i) => `studio-result-card-${i}`,
  },
  bulk: {
    root: "bulk-page",
    promptsTextarea: "bulk-prompts-textarea",
    csvUpload: "bulk-csv-upload",
    startBtn: "bulk-start-button",
    downloadZipBtn: "bulk-download-zip-button",
    item: (i) => `bulk-item-${i}`,
    itemStatus: (i) => `bulk-item-status-${i}`,
    modelSelect: "bulk-model-select",
    aspectSelect: "bulk-aspect-select",
    countInput: "bulk-count-input",
    presetSelect: "bulk-preset-select",
  },
  gallery: {
    root: "gallery-page",
    card: (id) => `gallery-card-${id}`,
    lightbox: "gallery-lightbox",
    lightboxDownload: "gallery-lightbox-download",
    lightboxCopyPrompt: "gallery-lightbox-copy-prompt",
    lightboxDelete: "gallery-lightbox-delete",
    lightboxRegenerate: "gallery-lightbox-regenerate",
    lightboxClose: "gallery-lightbox-close",
  },
  presets: {
    root: "presets-page",
    createBtn: "presets-create-button",
    card: (id) => `presets-card-${id}`,
    deleteBtn: (id) => `presets-delete-${id}`,
    useBtn: (id) => `presets-use-${id}`,
    dialogName: "presets-dialog-name",
    dialogUpload: "presets-dialog-upload",
    dialogDescription: "presets-dialog-description",
    dialogStrength: "presets-dialog-strength",
    dialogSaveBtn: "presets-dialog-save-button",
    dialogAnalyzeBtn: "presets-dialog-analyze-button",
  },
  settings: {
    root: "settings-page",
    keyInput: "settings-key-input",
    keySaveBtn: "settings-key-save-button",
    keyClearBtn: "settings-key-clear-button",
    mcpUrl: "settings-mcp-url",
    mcpToken: "settings-mcp-token",
    mcpCopyUrl: "settings-mcp-copy-url",
    mcpCopyToken: "settings-mcp-copy-token",
    mcpRegenerate: "settings-mcp-regenerate",
  },
  lightbox: {
    remixBtn: "lightbox-remix-button",
    shareBtn: "lightbox-share-button",
  },
  remix: {
    dialog: "remix-dialog",
    close: "remix-close",
    promptRow: (i) => `remix-prompt-${i}`,
    togglePrompt: (i) => `remix-toggle-${i}`,
    sendToBulk: "remix-send-to-bulk",
    regenerate: "remix-regenerate",
  },
  collections: {
    section: "collections-section",
    createBtn: "collections-create-button",
    chip: (id) => `collections-chip-${id}`,
    deleteBtn: (id) => `collections-delete-${id}`,
    dialogName: "collections-dialog-name",
    dialogSave: "collections-dialog-save",
    assignSelect: (presetId) => `collections-assign-${presetId}`,
  },
  share: {
    root: "share-page",
    image: "share-image",
    prompt: "share-prompt",
  },
};

// Re-export legacy testids for other consumers of this module (e.g. testing agent).
export * from "./auth";
export * from "./home";
